# file generated by ChatGPT 5.2 and approved by @314abh

# Compiler
CC = gcc
PKG_CONFIG = pkg-config

# Directories
SRC_DIR = .
OBJ_DIR = obj
BIN_DIR = bin

# Target
TARGET = $(BIN_DIR)/elite

# SDL3 flags
SDL3_CFLAGS = $(shell $(PKG_CONFIG) --cflags sdl3)
SDL3_LIBS   = $(shell $(PKG_CONFIG) --libs sdl3)

# Compiler / linker flags
CFLAGS = -std=c11 -Wall -Wextra $(SDL3_CFLAGS)
LDFLAGS = $(SDL3_LIBS) -lm

# Source files
SRC = $(wildcard $(SRC_DIR)/*.c)

# Object files inside obj/
OBJ = $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRC))

# Default target
all: $(TARGET)

# Link step
$(TARGET): $(OBJ) | $(BIN_DIR)
	$(CC) -o $@ $^ $(LDFLAGS)

# Compile step (place .o inside obj/)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	$(CC) $(CFLAGS) -c $< -o $@

# Create directories if missing
$(OBJ_DIR):
	mkdir -p $(OBJ_DIR)

$(BIN_DIR):
	mkdir -p $(BIN_DIR)

# Clean
clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)

.PHONY: all clean

